In [ ]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
sent = ['the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'i am a good boy',
        'i am a good developer',
        'understand']

In [ ]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'i am a good boy',
 'i am a good developer',
 'understand']

In [ ]:
len(sent)

6

In [ ]:
vocab_size=100

In [ ]:
vocab_size

100

In [ ]:
onehot_repr = [one_hot(word,vocab_size) for word in sent]

In [ ]:
onehot_repr

[[36, 92, 33, 32],
 [36, 92, 33, 80],
 [36, 67, 33, 94],
 [96, 88, 51, 50, 20],
 [96, 88, 51, 50, 63],
 [1]]

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [ ]:
import numpy as np

In [ ]:
sent_length = 8

In [ ]:
embedding_doc = pad_sequences(onehot_repr, padding = 'pre',maxlen = sent_length)

In [ ]:
print(embedding_doc)

[[ 0  0  0  0 36 92 33 32]
 [ 0  0  0  0 36 92 33 80]
 [ 0  0  0  0 36 67 33 94]
 [ 0  0  0 96 88 51 50 20]
 [ 0  0  0 96 88 51 50 63]
 [ 0  0  0  0  0  0  0  1]]


In [ ]:
#Features

In [ ]:
dim = 10

In [ ]:
model = Sequential()

In [ ]:
model.add(Embedding (vocab_size,10, input_length = sent_length))

In [ ]:
model.compile=('adam','mse')

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             1000      
Total params: 1,000
Trainable params: 1,000
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.predict(embedding_doc)

array([[[ 2.19306462e-02,  1.55628435e-02, -4.18432839e-02,
          4.33137268e-03, -2.44188197e-02,  2.63124444e-02,
         -1.54995546e-02,  4.79749180e-02,  5.15998527e-03,
          1.71290673e-02],
        [ 2.19306462e-02,  1.55628435e-02, -4.18432839e-02,
          4.33137268e-03, -2.44188197e-02,  2.63124444e-02,
         -1.54995546e-02,  4.79749180e-02,  5.15998527e-03,
          1.71290673e-02],
        [ 2.19306462e-02,  1.55628435e-02, -4.18432839e-02,
          4.33137268e-03, -2.44188197e-02,  2.63124444e-02,
         -1.54995546e-02,  4.79749180e-02,  5.15998527e-03,
          1.71290673e-02],
        [ 2.19306462e-02,  1.55628435e-02, -4.18432839e-02,
          4.33137268e-03, -2.44188197e-02,  2.63124444e-02,
         -1.54995546e-02,  4.79749180e-02,  5.15998527e-03,
          1.71290673e-02],
        [-1.09409690e-02, -2.27000955e-02, -1.71260722e-02,
         -2.81627774e-02, -8.07683542e-03,  4.88635190e-02,
          5.01079485e-03,  3.67532410e-02,  8.572563

In [ ]:
embedding_doc[0]

array([ 0,  0,  0,  0, 36, 92, 33, 32])

In [ ]:
model.predict(embedding_doc[0])

array([[[ 0.02193065,  0.01556284, -0.04184328,  0.00433137,
         -0.02441882,  0.02631244, -0.01549955,  0.04797492,
          0.00515999,  0.01712907]],

       [[ 0.02193065,  0.01556284, -0.04184328,  0.00433137,
         -0.02441882,  0.02631244, -0.01549955,  0.04797492,
          0.00515999,  0.01712907]],

       [[ 0.02193065,  0.01556284, -0.04184328,  0.00433137,
         -0.02441882,  0.02631244, -0.01549955,  0.04797492,
          0.00515999,  0.01712907]],

       [[ 0.02193065,  0.01556284, -0.04184328,  0.00433137,
         -0.02441882,  0.02631244, -0.01549955,  0.04797492,
          0.00515999,  0.01712907]],

       [[-0.01094097, -0.0227001 , -0.01712607, -0.02816278,
         -0.00807684,  0.04886352,  0.00501079,  0.03675324,
          0.00085726,  0.03068152]],

       [[-0.02117919,  0.02368097,  0.0174861 ,  0.00625514,
         -0.0066852 , -0.00077122, -0.0196106 , -0.04948808,
          0.04341162, -0.04853481]],

       [[ 0.04567954, -0.00490021, -0.01